version: '3.7'
services:
  app:
    depends_on:
      - mysql
    build:
      dockerfile: dev.Dockerfile
      context: .
    environment:
      DBPASSWORD: testsvcpassword
      DBHOST: mysql
      DBPORT: '3306'
      SECRET_KEY: 'very-secret-key'
      APP_DEBUG_MODE: 'True'
      JWT_AUDIENCE: https://joladnijo.jmsz.hu/api/
      JWT_KEYS: https://dev-ulmlyx6h.eu.auth0.com/.well-known/jwks.json
      JWT_ISSUER: https://dev-ulmlyx6h.eu.auth0.com/
    ports:
      - "8000:8000"
    volumes:
      - .:/code

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: testrootpassword
      MYSQL_USER: svc_backend
      MYSQL_PASSWORD: testsvcpassword
      MYSQL_DATABASE: joladnijo
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

volumes:
  mysql-data: