version: '3.7'
services:
  app:
    build:
      dockerfile: dev.Dockerfile
      context: .
    environment:
      DBNAME: joladnijo
      DBUSER: svc_backend
      DBPASSWORD: testsvcpassword
      DBHOST: mysql
      DBPORT: '3306'
      SECRET_KEY: 'very-secret-key'
      APP_DEBUG_MODE: 'True'
    ports:
      - "8000:8000"
    volumes:
      - .:/code:ro
  
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: testrootpassword
      MYSQL_PASSWORD: testsvcpassword
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

volumes:
  mysql-data: