version: '3.7'
services:
  app:
    depends_on:
      - mysql
    build:
      dockerfile: dev.Dockerfile
      context: .
    environment:
      ENVIRONMENT: development
      DBPASSWORD: testsvcpassword
      DBHOST: mysql
      DBPORT: '3306'
      SECRET_KEY: 'very-secret-key'
      APP_DEBUG_MODE: 'True'
      JWT_AUDIENCE: https://joladnijo.jmsz.hu/api/
      JWT_KEYS: https://dev-ulmlyx6h.eu.auth0.com/.well-known/jwks.json
      JWT_ISSUER: https://dev-ulmlyx6h.eu.auth0.com/
    ports:
      - "8000:8000"

  mysql:
    image: ghcr.io/joladnijo/mysql:5.7-1
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: testrootpassword
      MYSQL_USER: svc_backend
      MYSQL_PASSWORD: testsvcpassword
      MYSQL_DATABASE: joladnijo
