version: '3.7'
services:
  app:
    build: .
    environment:
      DBNAME: joladnijo
      DBUSER: svc_backend
      DBPASSWORD: testsvcpassword
      DBHOST: mysql
      DBPORT: '3306'
      SECRET_KEY: 'very-secret-key'
    ports:
      - "8000:8000"
  
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: testrootpassword
      MYSQL_PASSWORD: testsvcpassword

volumes:
  mysql-data: