# Generated by Django 3.2 on 2022-03-28 20:37

import uuid

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AidCenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField(blank=True, max_length=255, verbose_name='Megjegyzések')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Név')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                (
                    'photo',
                    models.FileField(blank=True, max_length=255, upload_to='aidcenter-photos', verbose_name='Kép'),
                ),
                ('country_code', models.CharField(max_length=5, verbose_name='Ország')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Irányítószám')),
                ('city', models.CharField(max_length=50, verbose_name='Település')),
                ('address', models.CharField(max_length=255, verbose_name='Cím')),
                (
                    'geo_location',
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326, verbose_name='Koordináták'
                    ),
                ),
                (
                    'call_required',
                    models.CharField(
                        blank=True,
                        choices=[('required', 'required'), ('suggested', 'suggested'), ('denied', 'denied')],
                        max_length=20,
                        null=True,
                        verbose_name='Hívás szükséges?',
                    ),
                ),
                ('campaign_ending_on', models.DateField(blank=True, null=True, verbose_name='Gyűjtés vége')),
            ],
            options={
                'verbose_name': 'Gyűjtőhely',
                'verbose_name_plural': 'Gyűjtőhelyek',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Név')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Ikon')),
            ],
            options={
                'verbose_name': 'Kategória',
                'verbose_name_plural': 'Kategóriák',
            },
        ),
        migrations.CreateModel(
            name='AssetRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField(blank=True, max_length=255, verbose_name='Megjegyzések')),
                ('name', models.CharField(max_length=255, verbose_name='Név')),
                (
                    'status',
                    models.CharField(
                        choices=[('requested', 'szükség van rá'), ('urgent', 'sürgős'), ('fulfilled', 'van elég')],
                        default='requested',
                        max_length=20,
                        verbose_name='Státusz',
                    ),
                ),
                (
                    'aid_center',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='joladnijo.aidcenter', verbose_name='Gyűjtőhely'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Adomány',
                'verbose_name_plural': 'Adományok',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Név')),
                (
                    'category',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='joladnijo.assetcategory',
                        verbose_name='Kategória',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Típus',
                'verbose_name_plural': 'Típusok',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField(blank=True, max_length=255, verbose_name='Megjegyzések')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Név')),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Szervezet',
                'verbose_name_plural': 'Szervezetek',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalOrganization',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('note', models.TextField(blank=True, max_length=255, verbose_name='Megjegyzések')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Név')),
                ('slug', models.SlugField(max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                (
                    'history_type',
                    models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
                ),
                (
                    'history_user',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'historical Szervezet',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalContact',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('note', models.TextField(blank=True, max_length=255, verbose_name='Megjegyzések')),
                ('name', models.CharField(max_length=255, verbose_name='Név')),
                ('email', models.EmailField(max_length=255, verbose_name='E-mail cím')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefonszám')),
                ('facebook', models.URLField(blank=True, max_length=255, verbose_name='Facebook profil')),
                ('url', models.URLField(blank=True, max_length=255, verbose_name='Egyéb url')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                (
                    'history_type',
                    models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
                ),
                (
                    'aid_center',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='joladnijo.aidcenter',
                        verbose_name='Gyűjtőhely',
                    ),
                ),
                (
                    'history_user',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='joladnijo.organization',
                        verbose_name='Szervezet',
                    ),
                ),
            ],
            options={
                'verbose_name': 'historical Kapcsolattartó',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalAssetRequest',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('note', models.TextField(blank=True, max_length=255, verbose_name='Megjegyzések')),
                ('name', models.CharField(max_length=255, verbose_name='Név')),
                (
                    'status',
                    models.CharField(
                        choices=[('requested', 'szükség van rá'), ('urgent', 'sürgős'), ('fulfilled', 'van elég')],
                        default='requested',
                        max_length=20,
                        verbose_name='Státusz',
                    ),
                ),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                (
                    'history_type',
                    models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
                ),
                (
                    'aid_center',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='joladnijo.aidcenter',
                        verbose_name='Gyűjtőhely',
                    ),
                ),
                (
                    'history_user',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'type',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='joladnijo.assettype',
                        verbose_name='Típus',
                    ),
                ),
            ],
            options={
                'verbose_name': 'historical Adomány',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalAidCenter',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('note', models.TextField(blank=True, max_length=255, verbose_name='Megjegyzések')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Név')),
                ('slug', models.SlugField(max_length=255)),
                ('photo', models.CharField(blank=True, max_length=255, verbose_name='Kép')),
                ('country_code', models.CharField(max_length=5, verbose_name='Ország')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Irányítószám')),
                ('city', models.CharField(max_length=50, verbose_name='Település')),
                ('address', models.CharField(max_length=255, verbose_name='Cím')),
                (
                    'geo_location',
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326, verbose_name='Koordináták'
                    ),
                ),
                (
                    'call_required',
                    models.CharField(
                        blank=True,
                        choices=[('required', 'required'), ('suggested', 'suggested'), ('denied', 'denied')],
                        max_length=20,
                        null=True,
                        verbose_name='Hívás szükséges?',
                    ),
                ),
                ('campaign_ending_on', models.DateField(blank=True, null=True, verbose_name='Gyűjtés vége')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                (
                    'history_type',
                    models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
                ),
                (
                    'history_user',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='joladnijo.organization',
                        verbose_name='Szervezet',
                    ),
                ),
            ],
            options={
                'verbose_name': 'historical Gyűjtőhely',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='FeedItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField(blank=True, max_length=255, verbose_name='Megjegyzések')),
                ('name', models.CharField(max_length=255, verbose_name='Név')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Ikon')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Időpont')),
                ('status_old', models.CharField(blank=True, max_length=255, verbose_name='Korábbi állapot')),
                ('status_new', models.CharField(blank=True, max_length=255, verbose_name='Új állapot')),
                (
                    'aid_center',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='joladnijo.aidcenter', verbose_name='Gyűjtőhely'
                    ),
                ),
                (
                    'asset_request',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='joladnijo.assetrequest',
                        verbose_name='Adomány',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Változás',
                'verbose_name_plural': 'Változások',
                'ordering': ['-timestamp'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField(blank=True, max_length=255, verbose_name='Megjegyzések')),
                ('name', models.CharField(max_length=255, verbose_name='Név')),
                ('email', models.EmailField(max_length=255, verbose_name='E-mail cím')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefonszám')),
                ('facebook', models.URLField(blank=True, max_length=255, verbose_name='Facebook profil')),
                ('url', models.URLField(blank=True, max_length=255, verbose_name='Egyéb url')),
                (
                    'aid_center',
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='joladnijo.aidcenter',
                        verbose_name='Gyűjtőhely',
                    ),
                ),
                (
                    'organization',
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='joladnijo.organization',
                        verbose_name='Szervezet',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Kapcsolattartó',
                'verbose_name_plural': 'Kapcsolattartók',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='type',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='joladnijo.assettype', verbose_name='Típus'
            ),
        ),
        migrations.AddField(
            model_name='aidcenter',
            name='organization',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='joladnijo.organization', verbose_name='Szervezet'
            ),
        ),
    ]
