# Generated by Django 3.2 on 2022-04-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joladnijo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidcenter',
            name='description',
            field=models.TextField(blank=True, max_length=255, verbose_name='Leírás'),
        ),
        migrations.AddField(
            model_name='historicalaidcenter',
            name='description',
            field=models.TextField(blank=True, max_length=255, verbose_name='Leírás'),
        ),
        migrations.AddField(
            model_name='historicalorganization',
            name='description',
            field=models.TextField(blank=True, max_length=255, verbose_name='Leírás'),
        ),
        migrations.AddField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, max_length=255, verbose_name='Leírás'),
        ),
    ]
