# Generated by Django 3.2 on 2022-03-21 22:54

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joladnijo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetType',
            fields=[],
            options={
                'verbose_name': 'Típus',
                'verbose_name_plural': 'Típusok',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('joladnijo.assetcategory',),
        ),
        migrations.AlterModelOptions(
            name='aidcenter',
            options={'verbose_name': 'Gyűjtőhely', 'verbose_name_plural': 'Gyűjtőhelyek'},
        ),
        migrations.AlterModelOptions(
            name='assetcategory',
            options={'verbose_name': 'Kategória', 'verbose_name_plural': 'Kategóriák'},
        ),
        migrations.AlterModelOptions(
            name='assetrequest',
            options={'verbose_name': 'Adomány', 'verbose_name_plural': 'Adományok'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Kapcsolattartó', 'verbose_name_plural': 'Kapcsolattartók'},
        ),
        migrations.AlterModelOptions(
            name='historicalaidcenter',
            options={
                'get_latest_by': 'history_date',
                'ordering': ('-history_date', '-history_id'),
                'verbose_name': 'historical Gyűjtőhely',
            },
        ),
        migrations.AlterModelOptions(
            name='historicalassetrequest',
            options={
                'get_latest_by': 'history_date',
                'ordering': ('-history_date', '-history_id'),
                'verbose_name': 'historical Adomány',
            },
        ),
        migrations.AlterModelOptions(
            name='historicalcontact',
            options={
                'get_latest_by': 'history_date',
                'ordering': ('-history_date', '-history_id'),
                'verbose_name': 'historical Kapcsolattartó',
            },
        ),
        migrations.AlterModelOptions(
            name='historicalorganization',
            options={
                'get_latest_by': 'history_date',
                'ordering': ('-history_date', '-history_id'),
                'verbose_name': 'historical Szervezet',
            },
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Szervezet', 'verbose_name_plural': 'Szervezetek'},
        ),
        migrations.RemoveField(
            model_name='aidcenter',
            name='money_accepted',
        ),
        migrations.RemoveField(
            model_name='aidcenter',
            name='money_description',
        ),
        migrations.RemoveField(
            model_name='assetcategory',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='assetrequest',
            name='category',
        ),
        migrations.RemoveField(
            model_name='assetrequest',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='historicalaidcenter',
            name='money_accepted',
        ),
        migrations.RemoveField(
            model_name='historicalaidcenter',
            name='money_description',
        ),
        migrations.RemoveField(
            model_name='historicalassetrequest',
            name='category',
        ),
        migrations.RemoveField(
            model_name='historicalassetrequest',
            name='icon',
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='category',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='joladnijo.assetcategory',
                verbose_name='Kategória',
            ),
        ),
        migrations.AlterField(
            model_name='aidcenter',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Cím'),
        ),
        migrations.AlterField(
            model_name='aidcenter',
            name='call_required',
            field=models.CharField(
                blank=True,
                choices=[('required', 'required'), ('suggested', 'suggested'), ('denied', 'denied')],
                max_length=20,
                null=True,
                verbose_name='Hívás szükséges?',
            ),
        ),
        migrations.AlterField(
            model_name='aidcenter',
            name='campaign_ending_on',
            field=models.DateField(blank=True, null=True, verbose_name='Gyűjtés vége'),
        ),
        migrations.AlterField(
            model_name='aidcenter',
            name='city',
            field=models.CharField(max_length=50, verbose_name='Település'),
        ),
        migrations.AlterField(
            model_name='aidcenter',
            name='country_code',
            field=models.CharField(max_length=5, verbose_name='Ország'),
        ),
        migrations.AlterField(
            model_name='aidcenter',
            name='geo_location',
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326, verbose_name='Koordináták'
            ),
        ),
        migrations.AlterField(
            model_name='aidcenter',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Név'),
        ),
        migrations.AlterField(
            model_name='aidcenter',
            name='note',
            field=models.TextField(blank=True, max_length=255, verbose_name='Megjegyzések'),
        ),
        migrations.AlterField(
            model_name='aidcenter',
            name='organization',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='joladnijo.organization', verbose_name='Szervezet'
            ),
        ),
        migrations.AlterField(
            model_name='aidcenter',
            name='photo',
            field=models.FileField(blank=True, max_length=255, upload_to='aidcenter-photos', verbose_name='Kép'),
        ),
        migrations.AlterField(
            model_name='aidcenter',
            name='postal_code',
            field=models.CharField(max_length=10, verbose_name='Irányítószám'),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='icon',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ikon'),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Név'),
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='aid_center',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='joladnijo.aidcenter', verbose_name='Gyűjtőhely'
            ),
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='is_urgent',
            field=models.BooleanField(verbose_name='Sürgős'),
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Név'),
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='note',
            field=models.TextField(blank=True, max_length=255, verbose_name='Megjegyzések'),
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='status',
            field=models.CharField(
                choices=[('requested', 'szükség van rá'), ('fulfilled', 'van elég'), ('overloaded', 'túl sok van')],
                default='requested',
                max_length=20,
                verbose_name='Státusz',
            ),
        ),
        migrations.AlterField(
            model_name='contact',
            name='aid_center',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='joladnijo.aidcenter',
                verbose_name='Gyűjtőhely',
            ),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='E-mail cím'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='facebook',
            field=models.URLField(blank=True, max_length=255, verbose_name='Facebook profil'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Név'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='note',
            field=models.TextField(blank=True, max_length=255, verbose_name='Megjegyzések'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='organization',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='joladnijo.organization',
                verbose_name='Szervezet',
            ),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefonszám'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='url',
            field=models.URLField(blank=True, max_length=255, verbose_name='Egyéb url'),
        ),
        migrations.AlterField(
            model_name='historicalaidcenter',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Cím'),
        ),
        migrations.AlterField(
            model_name='historicalaidcenter',
            name='call_required',
            field=models.CharField(
                blank=True,
                choices=[('required', 'required'), ('suggested', 'suggested'), ('denied', 'denied')],
                max_length=20,
                null=True,
                verbose_name='Hívás szükséges?',
            ),
        ),
        migrations.AlterField(
            model_name='historicalaidcenter',
            name='campaign_ending_on',
            field=models.DateField(blank=True, null=True, verbose_name='Gyűjtés vége'),
        ),
        migrations.AlterField(
            model_name='historicalaidcenter',
            name='city',
            field=models.CharField(max_length=50, verbose_name='Település'),
        ),
        migrations.AlterField(
            model_name='historicalaidcenter',
            name='country_code',
            field=models.CharField(max_length=5, verbose_name='Ország'),
        ),
        migrations.AlterField(
            model_name='historicalaidcenter',
            name='geo_location',
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326, verbose_name='Koordináták'
            ),
        ),
        migrations.AlterField(
            model_name='historicalaidcenter',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Név'),
        ),
        migrations.AlterField(
            model_name='historicalaidcenter',
            name='note',
            field=models.TextField(blank=True, max_length=255, verbose_name='Megjegyzések'),
        ),
        migrations.AlterField(
            model_name='historicalaidcenter',
            name='organization',
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='joladnijo.organization',
                verbose_name='Szervezet',
            ),
        ),
        migrations.AlterField(
            model_name='historicalaidcenter',
            name='photo',
            field=models.CharField(blank=True, max_length=255, verbose_name='Kép'),
        ),
        migrations.AlterField(
            model_name='historicalaidcenter',
            name='postal_code',
            field=models.CharField(max_length=10, verbose_name='Irányítószám'),
        ),
        migrations.AlterField(
            model_name='historicalassetrequest',
            name='aid_center',
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='joladnijo.aidcenter',
                verbose_name='Gyűjtőhely',
            ),
        ),
        migrations.AlterField(
            model_name='historicalassetrequest',
            name='is_urgent',
            field=models.BooleanField(verbose_name='Sürgős'),
        ),
        migrations.AlterField(
            model_name='historicalassetrequest',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Név'),
        ),
        migrations.AlterField(
            model_name='historicalassetrequest',
            name='note',
            field=models.TextField(blank=True, max_length=255, verbose_name='Megjegyzések'),
        ),
        migrations.AlterField(
            model_name='historicalassetrequest',
            name='status',
            field=models.CharField(
                choices=[('requested', 'szükség van rá'), ('fulfilled', 'van elég'), ('overloaded', 'túl sok van')],
                default='requested',
                max_length=20,
                verbose_name='Státusz',
            ),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='aid_center',
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='joladnijo.aidcenter',
                verbose_name='Gyűjtőhely',
            ),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='E-mail cím'),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='facebook',
            field=models.URLField(blank=True, max_length=255, verbose_name='Facebook profil'),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Név'),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='note',
            field=models.TextField(blank=True, max_length=255, verbose_name='Megjegyzések'),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='organization',
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='joladnijo.organization',
                verbose_name='Szervezet',
            ),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefonszám'),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='url',
            field=models.URLField(blank=True, max_length=255, verbose_name='Egyéb url'),
        ),
        migrations.AlterField(
            model_name='historicalorganization',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Név'),
        ),
        migrations.AlterField(
            model_name='historicalorganization',
            name='note',
            field=models.TextField(blank=True, max_length=255, verbose_name='Megjegyzések'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Név'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='note',
            field=models.TextField(blank=True, max_length=255, verbose_name='Megjegyzések'),
        ),
        migrations.DeleteModel(
            name='HistoricalAssetCategory',
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='type',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='joladnijo.assettype',
                verbose_name='Típus',
            ),
        ),
        migrations.AddField(
            model_name='historicalassetrequest',
            name='type',
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='joladnijo.assettype',
                verbose_name='Típus',
            ),
        ),
    ]
