# Generated by Django 3.2 on 2022-03-12 13:00

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joladnijo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidcenter',
            name='geo_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
