# Generated by Django 3.2 on 2022-03-21 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joladnijo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetType',
            fields=[],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('joladnijo.assetcategory',),
        ),
        migrations.RenameField(
            model_name='assetcategory',
            old_name='parent',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='assetrequest',
            name='category',
        ),
        migrations.RemoveField(
            model_name='assetrequest',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='historicalassetrequest',
            name='category',
        ),
        migrations.RemoveField(
            model_name='historicalassetrequest',
            name='icon',
        ),
        migrations.DeleteModel(
            name='HistoricalAssetCategory',
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='type',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='joladnijo.assettype'
            ),
        ),
        migrations.AddField(
            model_name='historicalassetrequest',
            name='type',
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='joladnijo.assettype',
            ),
        ),
    ]
