# Generated by Django 3.2 on 2022-03-22 20:04

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joladnijo', '0002_auto_20220321_2354'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField(blank=True, max_length=255, verbose_name='Megjegyzések')),
                ('name', models.CharField(max_length=255, verbose_name='Név')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Ikon')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Időpont')),
                ('status_old', models.CharField(blank=True, max_length=255, verbose_name='Korábbi állapot')),
                ('status_new', models.CharField(blank=True, max_length=255, verbose_name='Új állapot')),
                (
                    'aid_center',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='joladnijo.aidcenter', verbose_name='Gyűjtőhely'
                    ),
                ),
                (
                    'asset_request',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='joladnijo.assetrequest',
                        verbose_name='Adomány',
                    ),
                ),
            ],
            options={
                'ordering': ['-timestamp'],
                'verbose_name': 'Változás',
                'verbose_name_plural': 'Változások',
                'abstract': False,
            },
        ),
    ]
