# Generated by Django 3.2 on 2022-03-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joladnijo', '0002_aidcenter_geo_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidcenter',
            name='photo',
            field=models.FileField(blank=True, max_length=255, upload_to='aidcenter-photos'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='facebook',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='url',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
