name: Django Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: joladnijo
          MYSQL_ROOT_PASSWORD: joladnijo
          MYSQL_USER: svc_backend
          MYSQL_PASSWORD: joladnijo
        ports: ["3306:3306"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Migrations
        run: python manage.py migrate
        env:
          DBHOST: 127.0.0.1
          DBPASSWORD: joladnijo
          SECRET_KEY: "secret-key-for-build-pipeline"
      - name: Verify that Django is running
        run: |
              python manage.py runserver &
              STATUS=`curl -s -I http://127.0.0.1:8000/admin/login/?next=/admin/ | grep HTTP/1.1 | awk {'print $2'}`
              if [ $STATUS!="200" ] 
              then
                  exit 1
              fi
        env:
          DBHOST: 127.0.0.1
          DBPASSWORD: joladnijo
          SECRET_KEY: "secret-key-for-build-pipeline"
