name: Django Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: joladnijo
          MYSQL_DATABASE: joladnijo
        ports: ["3306:3306"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Migrations
        run: python manage.py migrate
        env:
          DBENGINE: django.db.backends.mysql
          DBNAME: joladnijo
          DBUSER: root
          DBPASSWORD: joladnijo
          DBHOST: 127.0.0.1
          DBPORT: 3306
          SECRET_KEY: "secret-key-for-build-pipeline"
